"use client";

import { Header } from "@/components/wrapped/Header";
import { BigStatCard } from "@/components/wrapped/BigStatCard";
import { ActivityStats } from "@/components/wrapped/ActivityStats";
import { DailyActivity } from "@/components/wrapped/DailyActivity";
import { MonthlyChart } from "@/components/wrapped/MonthlyChart";
import { TopTags } from "@/components/wrapped/TopTags";
import { GenreRadar } from "@/components/wrapped/GenreRadar";
import { MediaStatsSection } from "@/components/wrapped/MediaStatsSection";
import { TopMediaSection } from "@/components/wrapped/TopMediaSection";
import { mockUserData } from "@/data/wrapped.mock";

export default function WrappedPage() {
  const data = mockUserData;

  return (
    <div className='min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 text-slate-50'>
      <div className='w-full max-w-7xl mx-auto px-4 md:px-6 lg:px-8 py-6 space-y-8'>
        <Header user={data} />

        <main className='max-w-7xl mx-auto space-y-8'>
          <div className='grid grid-cols-1 lg:grid-cols-12 gap-6'>
            {/* Left Column */}
            <div className='lg:col-span-5 space-y-6'>
              <div className='grid grid-cols-1 sm:grid-cols-2 gap-5'>
                <BigStatCard
                  title='Total Anime Watched'
                  value={data.totalAnime}
                  unit='titles'
                  color='fuchsia'
                />
                <BigStatCard
                  title='Total Manga Read'
                  value={data.totalManga}
                  unit='titles'
                  color='orange'
                />
              </div>

              <div className='grid grid-cols-1 sm:grid-cols-2 gap-5'>
                <ActivityStats
                  daysActive={data.daysActive}
                  totalDays={data.totalDays}
                  mostActiveDay={data.mostActiveDay}
                  listActivity={data.listActivity}
                  statusPost={data.statusPost}
                />
                <DailyActivity
                  episodesPerDay={data.episodesPerDay}
                  chaptersPerDay={data.chaptersPerDay}
                  activityPerDay={data.activityPerDay}
                />
              </div>

              <MonthlyChart data={data.monthlyActivity} />

              <div className='grid grid-cols-1 sm:grid-cols-2 gap-5'>
                <TopTags tags={data.topTags} />
                <GenreRadar data={data.genreData} />
              </div>
            </div>

            {/* Right Column */}
            <div className='lg:col-span-7 space-y-6'>
              <MediaStatsSection type='anime' stats={data.animeStats} />
              <MediaStatsSection type='manga' stats={data.mangaStats} />
              <TopMediaSection title='Top Anime' items={data.topAnime} />
              <TopMediaSection title='Top Manga' items={data.topManga} />
            </div>
          </div>
        </main>

        <footer className='text-center text-gray-500 text-sm py-8'>
          <p>Generated by AniList Wrapped 2024</p>
        </footer>
      </div>
    </div>
  );
}
